version: '2.4'

services:

  frontend:
    image: ghcr.io/mathisburger/grocy-docker-frontend:latest
    depends_on:
      - backend
    ports:
      - '127.0.0.1:8080:8080'
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped

  backend:
    image: ghcr.io/mathisburger/grocy-docker-backend:latest
    expose:
      - '9000'
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - app-db:/var/www/data
    env_file:
      - grocy.env
    restart: unless-stopped

volumes:
  app-db:
