name: publish

on: [push]


jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: set up qemu
        uses: docker/setup-qemu-action@v1
      - name: set up buildx
        uses: docker/setup-buildx-action@v1
      - name: log in to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: mathisburger
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build backend
        uses: docker/build-push-action@v2
        with:
          push: true
          context: . 
          file: Containerfile-backend
          platforms: linux/arm64, linux/arm/v7
          tags: ghcr.io/mathisburger/grocy-docker-backend:${{ github.event.release.tag_name }}
      - name: Build backend
        uses: docker/build-push-action@v2
        with:
          push: true
          context: . 
          file: Containerfile-frontend
          platforms: linux/arm64, linux/arm/v7
          tags: ghcr.io/mathisburger/grocy-docker-frontend:${{ github.event.release.tag_name }}   
